% generation parameters (will override settings in Simulink HDL Coder model):
% e.g.:
%        'OptimizeForHDL',       'on',...
%        'ResetInputPort',       'rst_n',...
%        'ResetAssertedLevel',   'Active-low',... 
%        'GenerateHDLTestbench', 'on',...
%        'ResetAssertedLevel',   'Active-low',... 
%        'GenerateCoSimModel',   'ModelSim',...
% note: do not change TargetLanguage and TargetDirectory
gen_options = {...
        'OptimizeForHDL',       'on',...
        'GenerateHDLTestbench', 'on'};

