BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = $(TOOL)/lib_clock_controller_pll
DEPENDENCIES += $(TOOL)/lib_adc_receiver
DEPENDENCIES += $(TOOL)/lib_dac_control
DEPENDENCIES += $(TOOL)/lib_double_buffer
DEPENDENCIES += $(TOOL)/lib_channel_splitter
DEPENDENCIES += $(TOOL)/lib_channel_recombiner
#DEPENDENCIES += $(TOOL)/lib_FIR_filter
DEPENDENCIES += $(TOOL)/lib_IIR_filter

include $(BUILDFILES_PREFIX)/post_include.mk
