BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = $(TOOL)/lib_double_buffer
DEPENDENCIES += $(TOOL)/lib_clock_controller

include $(BUILDFILES_PREFIX)/post_include.mk
