BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = matlab/$(LIB_BLOCK)
SIM_HDL_SEARCH_PATH += ../../matlab/$(LIB_BLOCK)/hdl/$(BLOCK)_shell

include $(BUILDFILES_PREFIX)/post_include.mk
