BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = $(TOOL)/lib_adc_receiver
DEPENDENCIES += $(TOOL)/lib_clock_controller
DEPENDENCIES += $(TOOL)/lib_testbench_stimulus


include $(BUILDFILES_PREFIX)/post_include.mk
