BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = $(TOOL)/lib_top_audio_filter
DEPENDENCIES += $(TOOL)/lib_testbench_stimulus
DEPENDENCIES += $(TOOL)/lib_signal_gen
DEPENDENCIES += $(TOOL)/lib_dac_control


include $(BUILDFILES_PREFIX)/post_include.mk
