BUILDFILES_PREFIX=../../buildfiles
include $(BUILDFILES_PREFIX)/pre_include.mk

DEPENDENCIES = $(TOOL)/lib_clock_divider
DEPENDENCIES += $(TOOL)/lib_max_xci

include $(BUILDFILES_PREFIX)/post_include.mk
